export const products = [
  {
    id: 1,
    imageUrl:
      "https://strgimgr.umico.az/img/product/280/e029700d-3b75-40e7-a1eb-74998ef29077.jpeg",
    price: 200,
    description: "Reliable smartphone with long battery life and 6.6” display.",
    brand: "Iphone",
    title: "Iphone 17 Pro",
    category: "smartphone",
    addedToFavorite: true,
  },
    {
    id: 2,
    imageUrl: "https://strgimgr.umico.az/img/product/280/beba7fa9-6989-4dbd-b06d-c9ed3a627f81.jpeg",
    price: 350,
    description: "Powerful microfon with noise cancellation and clear sound.",
    brand: "AKG",
    title: "AKG 12",
    category: "audio",
    addedToFavorite: true,
  },
  {
    id: 3,
    imageUrl: "https://strgimgr.umico.az/img/product/280/9cbf8823-5034-44cc-99c4-8d34eb9b21fb.jpeg",
    price: 500,
    description: "High-end Notebook with triple camera and AMOLED display.",
    brand: "ASUS",
    title: "ASUS I8 Windows 11pro",
    category: "PC",
    addedToFavorite: true,
  },
  {
    id: 4,
    imageUrl: "https://strgimgr.umico.az/sized/280/974841-430084e1a424f8cbe4e3fbeb5d7d7c40.jpg",
    price: 280,
    description: "Affordable TV with 4K resolution and smart features.",
    brand: "TCL",
    title: "TCL Smart 2023",
    category: "TV",
    addedToFavorite: false,
  },
  {
    id: 5,
    imageUrl: "https://strgimgr.umico.az/img/product/280/64769473-5c71-4f20-8801-97658aa8a0a2.jpeg",
    price: 420,
    description: "Smartphone with 200MP camera and fast performance.",
    brand: "SAMSUNG",
    title: "SAMSUNG Galaxy S25 Ultra",
    category: "smartphone",
    addedToFavorite: false,
  },
  {
    id: 6,
    imageUrl: "https://strgimgr.umico.az/sized/280/476440-fabe0c22b6537035ba67326a0d8fef9f.jpg",
    price: 310,
    description: "microphone with deep bass and wireless connectivity.",
    brand: "AKG",
    title: "AKG Handle 9",
    category: "audio",
    addedToFavorite: false,
  },
   {
    id: 7,
    imageUrl: "https://strgimgr.umico.az/img/product/280/abf387d4-7d21-4ef8-82ee-bac220e70ea2.jpeg",
    price: 200,
    description: "made in Sheki",
    category: "smartphone",
    brand: "Redmi",
    title: "Samsung Galaxy A14",
    addedToFavorite: false,
  },
  {
    id: 8,
    imageUrl: "https://strgimgr.umico.az/img/product/280/dd64db31-1062-4b0c-bc6c-635b5706e60c.jpeg",
    price: 100,
    description: "made in Sumqait",
    category: "smartphone",
    brand: "Redmi",
    title: "Redmi 9A",
    addedToFavorite: false,
  },
  {
    id: 9,
    imageUrl: "https://strgimgr.umico.az/img/product/280/70a105ea-2593-4174-b510-f885454a3b8f.jpeg",
    price: 400,
    description: "made in Masazir",
    category: "smartphone",
    brand: "Redmi",
    title: "Redmi Honor 400 lite",
    addedToFavorite: false,
  },
  {
    id: 10,
    imageUrl: "https://storage.irshad.az/products/41273/21e44cdbefa3a93bb761c51ae37b6268.jpg",
    price: 50,
    description: "High-quality wireless mouse",
    category: "accessories",
    brand: "Logitech",
    title: "Logitech M185",
    addedToFavorite: false,
  },
  {
    id: 11,
    imageUrl: "https://strgimgr.umico.az/sized/840/926614-db0988acf087162f5030b15d8abe26f6.jpg",
    price: 120,
    description: "Mechanical keyboard with RGB",
    category: "accessories",
    brand: "Razer",
    title: "Razer BlackWidow V3",
    addedToFavorite: false,
  },
  {
    id: 12,
    imageUrl: "https://www.bakinity.biz/upload/iblock/742/nk1y2barcrc0utsww02zf098swkijzfi.jpg",
    price: 900,
    description: "Powerful laptop for work and gaming",
    category: "laptop",
    brand: "ASUS",
    title: "ASUS TUF Gaming F15",
    addedToFavorite: false,
  },
  {
    id: 13,
    imageUrl: "https://kaas.hpcloud.hp.com/PROD/v2/renderbinary/6489684/6489419/con-win-nb-p-weller-22c1-hp-envy-x360-laptop-15-ew0000-specification/con-nb-gidget-22c1-hp-envy-x360-15-es2000-product-image",
    price: 850,
    description: "Ultrabook with sleek design",
    category: "laptop",
    brand: "ASUS",
    title: "ASUS ZenBook 14",
    addedToFavorite: false,
  },
  {
    id: 14,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRncmHh7m9cmt1TyKNpyi-SJHg2CtA5uC9GIQ&s",
    price: 40,
    description: "Wireless earbuds with noise cancellation",
    category: "audio",
    brand: "Sony",
    title: "Sony WF-C500",
    addedToFavorite: true,
  }
];

export function getProductData() {
  return products;
}
